"use client";

import { BadgeCheck, Minus, Plus, RefreshCw, ShieldCheck, ShoppingBag, Users, WalletCards } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { PublicGroupView } from "@/lib/group-orders";
import { authorizeWithAmazonPay, type AmazonPayWebAuthorization } from "@/lib/amazon-pay-client";

const money = (paise: number) => `₹${(paise / 100).toFixed(2)}`;

export function GroupGuestExperience({ token }: { token: string }) {
  const [group, setGroup] = useState<PublicGroupView | null>(null);
  const [claims, setClaims] = useState<Record<string, number>>({});
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`/api/group-orders/public/${encodeURIComponent(token)}`); const data = await response.json(); if (response.ok) setGroup(data.group); else setError(data.error); }
  useEffect(() => {
    load();
    const url = new URL(window.location.href);
    const amazonResult = url.searchParams.get("amazon");
    if (amazonResult === "linked") setMessage("Amazon Pay account connected securely.");
    if (amazonResult === "error") setError("Amazon Pay authorization was cancelled or could not be completed.");
    if (amazonResult) { url.searchParams.delete("amazon"); window.history.replaceState({}, "", url); }
  }, [token]);
  useEffect(() => { if (group?.me) setClaims(Object.fromEntries(group.me.claims.map((claim) => [claim.lineId, claim.quantity]))); }, [group?.version, group?.me?.id]);
  const subtotal = useMemo(() => group?.items.reduce((sum, item) => sum + (claims[item.lineId] ?? 0) * item.unitPricePaise, 0) ?? 0, [claims, group]);
  async function join(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("join"); const displayName = String(new FormData(event.currentTarget).get("displayName") ?? ""); const response = await fetch(`/api/group-orders/public/${encodeURIComponent(token)}/participants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName }) }); const data = await response.json(); setBusy(""); if (response.ok) setGroup(data.group); else setError(data.error); }
  function change(item: PublicGroupView["items"][number], delta: number) { const mine = claims[item.lineId] ?? 0; const max = item.remaining + mine; setClaims((current) => ({ ...current, [item.lineId]: Math.max(0, Math.min(max, mine + delta)) })); }
  async function save() { if (!group) return; setBusy("save"); setError(""); const response = await fetch(`/api/group-orders/public/${encodeURIComponent(token)}/claims`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ version: group.version, claims: Object.entries(claims).map(([lineId, quantity]) => ({ lineId, quantity })) }) }); const data = await response.json(); setBusy(""); if (data.group) setGroup(data.group); if (response.ok) setMessage("Your choices are saved."); else setError(data.error); }
  async function amazonAction(action: "link" | "pay") { const contribution = group?.me?.contribution; const path = action === "link" ? "amazon/link" : `contributions/${contribution?.id}/pay`; setBusy(action); setError(""); const response = await fetch(`/api/group-orders/public/${encodeURIComponent(token)}/${path}`, { method: "POST" }); const data = await response.json(); if (!response.ok) { setBusy(""); return setError(data.error); } if (data.authorization) { try { await authorizeWithAmazonPay(data.authorization as AmazonPayWebAuthorization); } catch (error) { setBusy(""); setError(error instanceof Error ? error.message : "Could not open Amazon Pay."); } return; } setBusy(""); setGroup(data.group); setMessage(action === "link" ? "Amazon Pay linked for this sandbox session." : "Your share is paid. The owner can place the order when everyone is ready."); }

  if (!group && !error) return <main className="group-page group-loading"><RefreshCw /><h1>Opening the basket…</h1></main>;
  if (!group) return <main className="group-page"><section className="group-empty"><h1>Basket unavailable</h1><p>{error}</p></section></main>;
  if (!group.me) return <main className="group-page group-invite"><section className="page-enter"><div className="group-invite__art"><ShoppingBag /></div><span>PRIVATE NESTO BASKET</span><h1>{group.ownerName} invited you to shop</h1><p>Open the shared basket, claim the exact products you want, then pay only your merchant share through Amazon Pay.</p>{group.status === "draft" ? <form onSubmit={join}><label>Your name<input name="displayName" placeholder="What should we call you?" required minLength={2} maxLength={40} /></label><button className="group-primary" disabled={busy === "join"}>{busy === "join" ? "Joining…" : "Open the basket"}</button></form> : <p className="form-error">Choices are already locked.</p>}</section></main>;

  const contribution = group.me.contribution;
  return <main className="group-page"><header className="group-guest-head page-enter"><div><span>NESTO CIRCLE</span><h1>Hey {group.me.displayName}</h1><p>{group.status === "draft" ? "Claim the exact products you want from the shared basket." : group.status === "placed" ? "The delivery order is placed." : "Your Amazon Pay merchant share is ready."}</p></div><button onClick={load} aria-label="Refresh"><RefreshCw /></button></header>
    {group.status === "draft" ? <div className="group-guest-grid"><section className="group-card page-enter"><header><div><span>CHOOSE YOUR PRODUCTS</span><h2>What is yours?</h2></div></header><div className="group-claim-list">{group.items.map((item) => { const mine = claims[item.lineId] ?? 0; const max = item.remaining + mine; return <article key={item.lineId}><img src={item.image} alt="" /><div><strong>{item.name}</strong><small>{money(item.unitPricePaise)} · {item.remaining} available</small>{item.claimed.length > 0 && <em>{item.claimed.map((claim) => `${claim.displayName} × ${claim.quantity}`).join(" · ")}</em>}</div><div className="group-stepper" aria-label={`${item.name} quantity`}><button aria-label={`Remove one ${item.name}`} onClick={() => change(item, -1)} disabled={!mine}><Minus /></button><span>{mine}</span><button aria-label={`Add one ${item.name}`} onClick={() => change(item, 1)} disabled={mine >= max}><Plus /></button></div></article>; })}</div></section><aside className="group-control page-enter"><span>YOUR CURRENT SHARE</span><h2>{money(subtotal)}</h2><p>You can change quantities until {group.ownerName} locks the basket.</p><button className="group-primary" onClick={save} disabled={busy === "save"}>{busy === "save" ? "Saving…" : "Save my products"}</button>{message && <p className="group-message">{message}</p>}{error && <p className="form-error">{error}</p>}</aside></div> : contribution ? <section className="amazon-contribution page-enter"><div className="amazon-contribution__brand"><span>amazon</span><b>pay</b></div><span>YOUR MERCHANT SHARE</span><h1>{money(contribution.amountPaise)}</h1><p>Zaply charges your share directly for the products you claimed. Money is not deposited into another person’s Amazon Pay wallet.</p>{!group.me.amazonLinked ? <button className="amazon-button" onClick={() => amazonAction("link")} disabled={busy === "link"}><WalletCards />{busy === "link" ? "Connecting…" : "Continue with Amazon Pay"}</button> : contribution.status === "paid" ? <div className="amazon-paid"><BadgeCheck /><span><strong>Share paid</strong><small>{group.me.amazonInstrument}</small></span></div> : <><div className="amazon-instrument"><WalletCards /><span><strong>Amazon Pay connected</strong><small>{group.me.amazonInstrument}</small></span></div><button className="amazon-button amazon-button--pay" onClick={() => amazonAction("pay")} disabled={busy === "pay"}>{busy === "pay" ? "Confirming…" : `Pay ${money(contribution.amountPaise)}`}</button></>}<footer><ShieldCheck /> Zaply verifies the provider result before the order can be placed.</footer>{message && <p className="group-message">{message}</p>}{error && <p className="form-error">{error}</p>}</section> : <section className="group-empty"><Users /><h1>No share is due</h1><p>You did not claim any products before the basket was locked.</p></section>}
  </main>;
}
